### ISSUE TITLE
BUG: `split_search` does not split correctly in some cases

### ISSUE THREAD

**Issue by tkosciol** [biocore/microprot#71]
While benchmarking domain splitting between different approaches, I noticed that `split_search` script does not do some splits correctly.

Example on Barnacle: `/projects/microprot/results/domain_benchmark/pkg/01-PDB/T0831.{out,match,non_match}`
HHSearch clearly hits 1 PDB which should be the hit (residues "1-419" in target). However, for an unknown reason, the script decided to `match` residues "1-80" (*i.e. only the first line of alignment in out*) and leave "81-419" as a `non_match`. The problem then continues in `../02-CM`, where again we hit a single PDB with 100% probability, but the method only assigns `match` to residues "163-242" (i.e. only the second line*) and the rest is `non_match`

Parameters used:
```
split_PDB:
    params:
        min_prob: 95.0
        min_fragment_length: 40

split_CM:
    params:
        max_evalue: 0.1
        min_fragment_length: 40
```
or view the entire config on Barnacle in: `/projects/microprot/results/domain_benchmark/config.yml`

The fix is not very time-sensitive, but it would be nice to have before the end of the year.
